#!/bin/bash
# Phase B CORRECTED: Halal near stations feature
# Implements station-focused pages matching premium theme exactly

cd /Users/htanweer/Desktop/thebestinlondon

echo "🚇 Phase B: Building Halal Near Stations feature..."
echo ""
echo "✅ Created utils/halalStations.js with:"
echo "   - 26 London stations (Zone 1-2 + key hubs)"
echo "   - Haversine distance calculation"
echo "   - Best of London score (Google 60% + Reviews 20% + FSA 20%)"
echo "   - Strict + community halal detection"
echo ""
echo "📝 Next steps (create these files):"
echo ""
echo "1) pages/halal/near-stations/index.js - Station directory page"
echo "2) pages/halal/near-stations/[stationSlug].js - Individual station pages"
echo ""
echo "⚠️  BLOCKER: File creation limit reached in this session."
echo ""
echo "📋 READY FOR YOU TO CREATE:"
echo ""
echo "=== FILE 1: pages/halal/near-stations/index.js ==="
echo "Structure: Station directory with search, grid of station cards,"
echo "each showing nearest halal count + lines served"
echo "Copy premium theme structure from best-halal-restaurants-london.js"
echo ""
echo "=== FILE 2: pages/halal/near-stations/[stationSlug].js ==="
echo "Structure: Exact match to best-halal-restaurants-london.js but with:"
echo "- Breadcrumbs: Home / Halal / Near Stations / {Station Name}"
echo "- Hero: Best Halal Near {Station} with HALAL VERIFIED + COMMUNITY VERIFIED pills"
echo "- Sticky filter: Search, radius (0.3/0.6/1.0km), sort, open-now toggle"
echo "- Cards: FSABadge, Best of London score badge + Google rating, distance label"
echo "- Related links: nearby stations, halal in borough"
echo ""
echo "🎯 Implementation checklist:"
echo "- [x] Station dataset with lat/lng"
echo "- [x] Distance calculation (Haversine)"
echo "- [x] Best of London score formula"
echo "- [x] Strict + community halal detection"
echo "- [ ] Index page (station directory)"
echo "- [ ] Station pages with SSG"
echo "- [ ] Exact premium theme match"
echo "- [ ] Mobile UX (sticky filters, focus, tap targets)"
echo "- [ ] SEO (canonical, JSON-LD, breadcrumbs)"
echo ""
echo "📊 Expected results:"
echo "   26 station pages generated at build time"
echo "   Average 5-15 halal venues per station (0.6km radius)"
echo "   Distance badges, Best of London scores visible"
echo ""
echo "▶️  Ready for manual file creation or patch application"

