name = "thebestinlondon"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

# Environment variables (set in Cloudflare dashboard after deployment)
# NEXT_PUBLIC_GOOGLE_PLACES_KEY = "your-key-here"
